export const HANDLE_SEARCH = 'handle_search';
export const GET_INITIAL_MOVIES = "get_initial_movies";
export const HANDLE_NEXT_PAGE = "handle_next_page";
export const HANDLE_PREVIOUS_PAGE = "handle_previous_page";
export const HANDLE_IMAGE_CLICK = 'handle_image_click';
export const HANDLE_SIDEBAR = 'handle_sidebar';
export const HANDLE_RESET = "handle_reset";
export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error'
export const SIGN_OUT = 'sign_out';
export const SEARCH_ERROR= "search_error";
export const GET_FAVES = "get_faves";
export const SAVED_MOVIE = "saved_movie";
export const DELETE_MOVIE = "delete_movie"
export const RESET_ERROR_MSG = "reset_error_msg";